name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
    #x32 for sourcemod
      run: docker build . --file bookworm/x32/Dockerfile --tag owotf2:$(date +%s)
